# Generated by Django 3.2.22 on 2023-10-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_auto_20231016_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricat',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Свободный остаток'),
        ),
    ]
