# Generated by Django 3.2.22 on 2023-10-18 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0011_auto_20231019_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productparameter',
            options={'verbose_name': 'Параметр товара', 'verbose_name_plural': 'Список параметров товара'},
        ),
    ]
