# Generated by Django 3.2.22 on 2023-10-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0011_auto_20231019_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Заказанная позиция', 'verbose_name_plural': 'Список заказанных позиций'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-article', '-name', '-category'), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Перечень номенклатуры'},
        ),
        migrations.AlterModelOptions(
            name='productparameter',
            options={'verbose_name': 'Параметр товара', 'verbose_name_plural': 'Список параметров товара'},
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('article', 'name'), name='unique_product_name'),
        ),
    ]
