# Generated by Django 3.2.22 on 2023-10-30 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0016_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-name',), 'verbose_name': 'Категория(Category)', 'verbose_name_plural': 'Список категорий'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакты пользователя(Contact)', 'verbose_name_plural': 'Список контактов пользователя'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',), 'verbose_name': 'Заказ(Order)', 'verbose_name_plural': 'Список заказов'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Заказанная позиция(OrderItem)', 'verbose_name_plural': 'Список заказанных позиций'},
        ),
        migrations.AlterModelOptions(
            name='parameter',
            options={'ordering': ('-name',), 'verbose_name': 'Название параметра(Parameter)', 'verbose_name_plural': 'Список названий параметров'},
        ),
        migrations.AlterModelOptions(
            name='pricat',
            options={'verbose_name': 'Данные о продукте(Pricat)', 'verbose_name_plural': 'Список данных о продуктах'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-article', '-name', '-category'), 'verbose_name': 'Продукт(Product)', 'verbose_name_plural': 'Перечень номенклатуры'},
        ),
        migrations.AlterModelOptions(
            name='productparameter',
            options={'verbose_name': 'Параметр товара(ProductParameter)', 'verbose_name_plural': 'Список параметров товара'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['-name'], 'verbose_name': 'Магазин(Shop)', 'verbose_name_plural': 'Список магазинов'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('email',), 'verbose_name': 'Пользователь(User)', 'verbose_name_plural': 'Список пользователей'},
        ),
    ]
