# Generated by Django 3.2.22 on 2023-10-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0018_auto_20231030_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_product',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
