# Generated by Django 3.2.22 on 2023-11-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0021_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
