# Generated by Django 3.2.22 on 2023-11-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0022_shop_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка для загрузки приката'),
        ),
    ]
